### ISSUE TITLE
May I help you update styling register page

### ISSUE THREAD

**Issue by karitthorn** [arcVaishali/stellar-vision#12]
![Screenshot 2566-10-13 at 21 47 18](https://github.com/arcVaishali/stellar-vision/assets/56643494/e9066b3f-d9be-4013-8ada-4441fcd2514a)

by change input text style , Make the logo picture symmetrical and etc. 

Thank You👍

**Comment by arcVaishali** [comment]
Hello **@karitthorn** ! We are assigning you this issue, kindly resolve this issue on time. Also don't change the registration info we have decided to take from the rescuers now.

**Comment by MrDBC** [comment]
@arcVaishali Can you look into my PR and see if you need some changes in the UI?

**Comment by karitthorn** [comment]
👍
