### ISSUE TITLE
Add  Attractive Footer

### ISSUE THREAD

**Issue by Bisalkumar1** [arcVaishali/stellar-vision#19]
I can add an attractive and responsive  footer to your project.
kindly assign this to me under hacktoberfest.

**Comment by arcVaishali** [comment]
Hello @Bisalkumar1 ! Welcome to Relief Connect. We are assigning you this issue, make sure to follow the Contributing Guidelines.

**Comment by MrDBC** [comment]
@Bisalkumar1 
 There's no footer in the app
could u elaborate more on what u intend to do?

**Comment by arcVaishali** [comment]
Checkout this design template, we need something similar to this, https://disasterrelief.webflow.io/

Here is our ppt explaining what we intend to do- https://www.canva.com/design/DAFos__N-es/gUn89J-6JxPkbKy4WrTvLg/edit
and here you can check out our devpost story and know what we have completed in this project and what is still left to complete- https://devpost.com/software/relief-connect

**Comment by arcVaishali** [comment]
Also please work only on footer for now.

**Comment by Sanketmane2323** [comment]
Hey i would like to contribute to these issues.

**Comment by Bisalkumar1** [comment]
ok will add and update thanks for assigning this to me

**Comment by Bisalkumar1** [comment]
> Also please work only on footer for now and make it responsive as well.

ok will add and update thanks for assigning this to me

**Comment by Bisalkumar1** [comment]
#19 solved
