### ISSUE TITLE
Inconsistency in image switching tabs

### ISSUE THREAD

**Issue by Seemant-RajSingh** [arcVaishali/stellar-vision#40]
![Screenshot 2023-10-16 181359](https://github.com/arcVaishali/stellar-vision/assets/117286608/f85d0b2a-1518-4690-9b5b-491482bb390c)

As you can see in the above image, the highlighted (red circle) shows an inconsistency in the image switching tabs (black dots), which should be one tab at all times have a bug, the selected dot always remain highlighted despite auto image switching.

I would like to fix this bug, kindly assign me this project under hacktoberfest 2023.

**Comment by Aniket3063** [comment]
hey @arcVaishali , can you assign this issue to me.
also i want to fix the improper image size in slider in mobile view and both the icons in navbar are just directing to instagram.
![image](https://github.com/arcVaishali/stellar-vision/assets/97459528/afaea35c-c0a2-47a7-b6cb-a1d6c04ae276)

**Comment by arcVaishali** [comment]
> hey @arcVaishali , can you assign this issue to me. also i want to fix the improper image size in slider in mobile view and both the icons in navbar are just directing to instagram. ![image](https://user-images.githubusercontent.com/97459528/276098966-afaea35c-c0a2-47a7-b6cb-a1d6c04ae276.png)

@Aniket3063 pls create a separate issue for this.

**Comment by Seemant-RajSingh** [comment]
pull request for the tab switching issue has been made, refer https://github.com/arcVaishali/stellar-vision/pull/66
