### ISSUE TITLE
Button style as website theme

### ISSUE THREAD

**Issue by Seemant-RajSingh** [arcVaishali/stellar-vision#45]
![image](https://github.com/arcVaishali/stellar-vision/assets/117286608/776e53da-8fd9-4cb9-aac5-52715a89fdb5)
The button can be styled for a better suit to the website theme.
Kindly assign this under hacktoberfest.

**Comment by arcVaishali** [comment]
Please show us your designs first.

**Comment by Seemant-RajSingh** [comment]
Button design:

button without hover shown below
![image](https://github.com/arcVaishali/stellar-vision/assets/117286608/776eab98-489b-484e-9e0f-f8bd098ae91e)

button after hover (**opacity increased, shadow effect added, button size increases**):
![image](https://github.com/arcVaishali/stellar-vision/assets/117286608/bca693d3-58a7-420b-ac79-1ddd30c41dc9)

1. the button design is now more suited to the website theme
2. The slider was preventing hover properties from displaying, issue has been fixed.

if you have any additional/other design in mind, i will be happy to work on it.

**Comment by Seemant-RajSingh** [comment]
@malay5 , Differently styled buttons and styled Carousel sliders have already been added for pull requests before,
requesting @arcVaishali to go through it once.

**Comment by arcVaishali** [comment]
@Seemant-RajSingh we like these designs better than the existing once, we are assigning you this issue, make sure to complete it on time and follow the contributing guidelines.

**Comment by Seemant-RajSingh** [comment]
@arcVaishali a pull request for issue #42 has already been made, includes:
1. styled mycarousel
2. button style updated as per request

please refer PR https://github.com/arcVaishali/stellar-vision/pull/62

the button style in issue 42 is different than the one shown above, if you prefer this design, i can update the button design in #42 and remake the pull request.

**Comment by arcVaishali** [comment]
Yeah sure change the button design

**Comment by arcVaishali** [comment]
Create one more PR
